Github Actions: Adds pull_request and ruby 3.1
Mange/roadie-rails pull request #104
Opened 2022-01-29 12:01 UTC by davidwessman

- Trigger actions on pull_request (should still need maintainer
  permission first time to run).
- Adds ruby 3.1 to testing matrix.

2022-01-31 10:25 UTC, Mange commented
Looks good. Tests fail on Rails 6.0, though. Maybe we need to change "max Ruby version" for that app?

2022-01-31 10:26 UTC, Mange requested changes

2022-01-31 10:26 UTC, Mange commented on .github/workflows/main.yml
> +        ruby: ["2.6", "2.7", "3.0", "3.1"]
It would be great to have Changelog and README updated too.

2022-01-31 10:59 UTC, davidwessman commented
> Looks good. Tests fail on Rails 6.0, though. Maybe we need to change "max Ruby version" for that app?

It fails because of net/smtp being extracted to separate gem in Ruby 3.1. Do you have any idea how we should specify it being a dependency? Would it be enough to add it as development dependency in the gemspec?

Will update with changelog 🙂

2022-01-31 13:09 UTC, Mange commented
> It fails because of net/smtp being extracted to separate gem in Ruby 3.1. Do you have any idea how we should specify it being a dependency? Would it be enough to add it as development dependency in the gemspec?

Hmm, though one. It's not really our problem since it's Rails using that dependency, and it would be weird to depend on a gem we don't use.

Better that we try to add it as a dependency inside the nested Rails 6.0 app, I think. Perhaps we could even include it conditionally in the nested Gemfile needed.

2022-01-31 14:40 UTC, davidwessman commented
> 

I realized Ruby 3.1 failed for both Rails 6.0 and 6.1, which is not officially supported, so I limited to only run Rails 7.0 on Ruby 3.1. 

Please review the changes to README, CHANGELOG and also the version-references.

I see that there is a mix of e.g. single and double quotes in the test-apps. How do you feel about adding a formatter?

I have used both:
- https://github.com/testdouble/standard
- https://github.com/prettier/plugin-ruby (requires Node)

2022-02-02 19:35 UTC, Mange approved these changes
It looks great. Thank you!

2022-02-02 19:35 UTC, merged

2022-02-02 19:36 UTC, Mange commented
> I see that there is a mix of e.g. single and double quotes in the test-apps. How do you feel about adding a formatter?

I have not minded as much as it's just test fixtures generated by Rails itself.

I use `standardrb` for all my Ruby projects nowadays, and have to have a hack to disable it from autoformatting in the Roadie projects since it's just under passive maintenance.

It's probably time to fix that…

2022-02-02 21:09 UTC, Mange commented
A new version of `roadie-rails` was just released.